### ISSUE TITLE
Support Java 8 Instant's in addition to older Date's

### ISSUE THREAD

**Issue by mcandre** [DiUS/java-faker#111]
Please include support for Java 8 Instants, to make it easier for newer developers to plug and play.

**Comment by codingricky** [comment]
I want to keep Java 1.6 support. For legacy and also Android support reasons.

**Comment by mcandre** [comment]
Understood. Could we fork java-faker for Java 8+ types?

**Comment by codingricky** [comment]
@mcandre I don't think it's worth the overhead of forking and maintaining 2 branches for the purpose of Java 8 types at the moment. Maybe when there is sufficient demand for it, I will reconsider the position.

**Comment by mih-kopylov** [comment]
@codingricky isn't it the time to reconsider using `java.time` package as a default for `DateAndTime` values?

**Comment by bodiam** [comment]
@mih-kopylov  we've made a start with this at www.datafaker.net, a fork of Java faker, have a look at the Time class. If something is missing lease let us know or send a PR!

**Comment by mih-kopylov** [comment]
Good to know, thanks!
