### ISSUE TITLE
Phone numbers often contain invalid country codes

### ISSUE THREAD

**Issue by mcandre** [DiUS/java-faker#112]
Could faker provide two phone number generators, one with guaranteed valid country codes, another with potentially invalid country codes?

**Comment by codingricky** [comment]
@mcandre yes that's fair enough. The phone numbers are randomly generated numbers.

**Comment by trevershick** [comment]
This is a pretty big request.  It would be better to migrate this in locale by locale. Phone number rules are complicated (like Finland) so doing all the research for all countries/locales is a big time suck.

Is there a specific set/subset of locales you are working with @mcandre ?

If you would be willing to enumerate the rules in this issue the fix will get put in that much quicker (I started to look but there are a lot of rules).  I'll happily fix any provided someone does the legwork to get the rules.

**Comment by codingricky** [comment]
Closing this issue as there is no feedback wrt any specific locales and rules. Once there are some specific rules we can open another issue.
