### ISSUE TITLE
Upgrade to commons-lang3

### ISSUE THREAD

**Issue by mlschechter** [DiUS/java-faker#116]
The `java-faker` code currently pulls in the older `commons-lang` classes and functionality. This can create issues in projects that want to exclusively use `commons-lang3` and `java-faker`.

Could you please upgrade the dependency?

**Comment by codingricky** [comment]
Do you want to submit a pull request?

**Comment by mlschechter** [comment]
Yes, I can do that. 

One question: The `RandomUtils` class has been changed significantly. The API has been narrowed, and injection of a `Random` instance is no longer supported. To continue providing the functionality you have in place, I'd recommend switching over to using the injected `Random` instance directly. Could you please let me know if you see any issue with this?

Thanks!

**Comment by mlschechter** [comment]
Thanks for pushing this through. Could you please let me know when the next release will be?
