### ISSUE TITLE
randomDouble failed when max or min is really big/small

### ISSUE THREAD

**Issue by nielinjie** [DiUS/java-faker#120]
Please check -
```
number().randomDouble(0,int.MaxValue,int.MinValue)
```
I think the reason is max-min is out of integer's scope.

**Comment by trevershick** [comment]
I've written a test and it works fine
```

        final Double v = faker.number().randomDouble(0, Integer.MAX_VALUE, Integer.MIN_VALUE);
        final Double v2 = faker.number().randomDouble(0, Integer.MIN_VALUE, Integer.MAX_VALUE);
        
        assertThat(v, is(not(nullValue())));
        assertThat(v2, is(not(nullValue())));

```

What sort of error did you get?  Are you using the standard Faker() constructor or are you using a custom Random in the parameters?

**Comment by nielinjie** [comment]
Sorry for late replay. This problem is no about error will be thrown, but the result is not really random. See this code please  -


//your original version.

>    public double randomDouble2(int maxNumberOfDecimals, int min, int max) {
        double value = min + (max - min) * randomService.nextDouble();
        return new BigDecimal(value).setScale(maxNumberOfDecimals, BigDecimal.ROUND_HALF_EVEN).doubleValue();
    }

//My quick version.

> public double randomDouble(int maxNumberOfDecimals, int min, int max) {
        long mm= (long)max - (long)min;
        double value = (double) min + mm * randomService.nextDouble();
        return new BigDecimal(value).setScale(maxNumberOfDecimals, BigDecimal.ROUND_HALF_EVEN).doubleValue();
    }

//calling them.

> Faker faker = new Faker();
        for (int i = 0; i < 10; i++) {
            double re = faker.number().randomDouble2(0, Integer.MAX_VALUE, Integer.MIN_VALUE);
            System.out.println(re);
        }
        System.out.println("////////");
        for (int i = 0; i < 10; i++) {
            double re = faker.number().randomDouble(0, Integer.MAX_VALUE, Integer.MIN_VALUE);
            System.out.println(re);
        }

///////////result - 

2.147483648E9
2.147483648E9
2.147483647E9
2.147483648E9
2.147483647E9
2.147483647E9
2.147483647E9
2.147483648E9
2.147483648E9
2.147483648E9
////////
-9.82605068E8
-8.30306153E8
-4.5085583E7
2.11132407E9
1.632605795E9
1.03563329E8
-1.071310702E9
8.69193743E8
2.32414918E8
-7.97170719E8
