### ISSUE TITLE
FakeValuesServiceTest#expressionWithValidFakerObjectValidMethodInvalidArgs unit test fails

### ISSUE THREAD

**Issue by PascalSchumacher** [DiUS/java-faker#143]
Locally this test always fails with:

>expressionWithValidFakerObjectValidMethodInvalidArgs(com.github.javafaker.service.FakeValuesServiceTest)  Time elapsed: 0.029 sec  <<< FAILURE!
>java.lang.AssertionError:
>Expected: is "Unable to coerce x to Long via Long(String) constructor."
>     but: was "Unable to coerce x to Integer via Integer(String) constructor."

**Comment by codingricky** [comment]
It doesn't always fail for me. I've seen it fail once. There's something in there causing it to be non deterministic.

**Comment by PascalSchumacher** [comment]
For me it failed 5 times in a row before I created the issue. I just ran the test again and now it passes.

**Comment by trevershick** [comment]
I'm in Orlando right now. My guess is that when getting the list of methods from the class, it returns in an inconsistent order. I have an enhancement I've worked out in my head to addresss this issue.
