### ISSUE TITLE
maven download does not seem to be working

### ISSUE THREAD

**Issue by iceddante** [DiUS/java-faker#157]
`Could not find artifact com.github.bmoliveira:snake-yaml:jar:v1.18-android in mavenCentral (https://repo1.maven.org/maven2/)`

I am getting this error message when trying to install the project. Is anyone else having this issue? Here's my repository setup:
```

    repositories {
        inherits true
        mavenCentral()
        grailsPlugins()
        grailsHome()
        mavenLocal()
        mavenRepo "http://repo.grails.org/grails/core"
        grailsCentral()
    }
```
for the following dependency:
`compile "com.github.javafaker:javafaker:0.11"`

**Comment by trevershick** [comment]
Try adding jitpack to your repos. 
allprojects {
    repositories {
    ...
    maven { url "https://jitpack.io" }

**Comment by PascalSchumacher** [comment]
or use `compile "com.github.javafaker:javafaker:0.11:deps"`

**Comment by zezuha** [comment]
I had this problem recently. When switching from 0.10 to 1.11.

As above, I had to add Jitpack and then snake-yaml from com.github.bmoliveira.

In my case, SBT, I actually had to add "1.18.1-android-rc2". SBT somehow was stripping out the prefix v from v1.18 as recommended by BMoliveira.

**Comment by iceddante** [comment]
Thanks guys: I added jitpack as a maven destination to fix it.
Pascal: I'm not familiar with the 'deps' suffix. I'll have to look that up. Thanks!

**Comment by viswagb** [comment]
import com.github.javafaker . not working with below dependency ..

	//compile "com.github.javafaker:javafaker:0.11:deps"
	//implementation 'com.github.javafaker:javafaker:1.0.1'

**Comment by viswagb** [comment]
>>maven { url "https://jitpack.io" }

this worked
