### ISSUE TITLE
Resource loading fails on Android

### ISSUE THREAD

**Issue by christopherperry** [DiUS/java-faker#16]
Simply newing up a `Faker` on Android causes failure during resource loading of the yaml file. To keep your implementation clean of Android specifics please either make the `findStream()` method package private or public so it can be overriden.

**Comment by PascalSchumacher** [comment]
Just to let everybody know, the next version of java-faker 0.10 will work on android out of the box: https://github.com/DiUS/java-faker/commit/f4bb18940c833fc63008b50ffe03024efdcfd480

Cheers,
Pascal

**Comment by PascalSchumacher** [comment]
java-faker 0.10 with Android support has been released: https://github.com/DiUS/java-faker/commit/8e92962b401436c5f4afd1094996659e62204044
