### ISSUE TITLE
Flawed random number generation

### ISSUE THREAD

**Issue by Eluinhost** [DiUS/java-faker#176]
Random number generation doesn't fill the full spectrum, it misses values at the end of the range. For example numberBetween(1,4) will only generate values of 1 and 2, no 3 will show up. 

Was testing with this code (sorry it's scala):

```
(0 until 1000000)
        .map(_ ⇒ number.numberBetween(i1, i2))
        .groupBy(it ⇒ it)
        .mapValues(_.size)
        .toList
        .sortBy(_._1)
        .map(e ⇒ s"${e._1} ⇒ ${e._2}")
        .mkString(sep = "\n")
```

Example output for 1/4:

```
1 ⇒ 577767
2 ⇒ 422233
```

Again with 1/9:

```
1 ⇒ 177079
2 ⇒ 176831
3 ⇒ 176511
4 ⇒ 177270
5 ⇒ 175808
6 ⇒ 116501
```

This final value is always lower in distribution also.

Testing it with number.randomDouble(2, 1, 4) instead shows that it only generates up to 2.73 (this time with 1.0 and 2.73 always statistically below the other entries). I'm assuming the imbalance above is due to values 2 to 2.73 being truncated to 2.

```
1.0 ⇒ 2896
1.01 ⇒ 5844
1.02 ⇒ 5743
1.03 ⇒ 5730
1.04 ⇒ 5922
1.05 ⇒ 5707
1.06 ⇒ 5662
1.07 ⇒ 5815
1.08 ⇒ 5932
1.09 ⇒ 5709
1.1 ⇒ 5703
1.11 ⇒ 5645
1.12 ⇒ 5822
1.13 ⇒ 5842
1.14 ⇒ 5745
1.15 ⇒ 5841
1.16 ⇒ 5658
1.17 ⇒ 5858
1.18 ⇒ 5866
1.19 ⇒ 5771
1.2 ⇒ 5767

...

2.64 ⇒ 5723
2.65 ⇒ 5595
2.66 ⇒ 5829
2.67 ⇒ 5670
2.68 ⇒ 5751
2.69 ⇒ 5702
2.7 ⇒ 5807
2.71 ⇒ 5769
2.72 ⇒ 5731
2.73 ⇒ 4154
```

I've not looked hard at it but I'm assuming that this is related to this section of code https://github.com/DiUS/java-faker/blob/master/src/main/java/com/github/javafaker/Number.java#L99 and maybe it is unable to select things in the final 'chunk'.

I tested with ranges that are square numbers and the integer version works correctly:

1/10:

```
1 ⇒ 111236
2 ⇒ 110611
3 ⇒ 111531
4 ⇒ 111096
5 ⇒ 111473
6 ⇒ 110981
7 ⇒ 110982
8 ⇒ 110801
9 ⇒ 111289
```

And the double version is close, the first and last entries are lower than the rest of the range:

```
1.0 ⇒ 1279
1.01 ⇒ 2508
1.02 ⇒ 2423
1.03 ⇒ 2519
1.04 ⇒ 2477

...


4.97 ⇒ 2517
4.98 ⇒ 2516
4.99 ⇒ 2596
5.0 ⇒ 1287
```

**Comment by PascalSchumacher** [comment]
@codingricky Looks like this issue was duplicated by https://github.com/DiUS/java-faker/issues/214 which you fixed with https://github.com/DiUS/java-faker/commit/694ea43e2befe9c7ebc44ffec376dc70dba1f409

So I guess this can be closed too.
