### ISSUE TITLE
Wrapping sublists with Serializable collections

### ISSUE THREAD

**Issue by Abrasha** [DiUS/java-faker#177]
I guess it is better to replace `words.subList(0, num)` with `new ArrayList(words.subList(0, num))` in

    public List<String> words(int num) {
        List<String> words = (List<String>) fetchObject("lorem.words");
        Collections.shuffle(words);
        return words.subList(0, num);
    }

and similar to it.
Because there are cases when we have such exception:

    java.io.NotSerializableException: java.util.ArrayList$SubList

Because `ArrayList$SubList` does not implement `Serializable`.
In this way, user has to wrap fake string list with `ArrayList` manually.
And code looks like the following:

    new ArrayList<>(faker.words(3))

I understand, that fake data is mostly read-only and is not serialized often.

What do you think about it?

**Comment by trevershick** [comment]
I would say that as a general principal, if you're going to be serializing objects then you should be explicitly managing this sort of thing in your code.  To rely upon an external library would be dangerous.  It's with best intentions that libraries are maintained and coverage can be added to the library but stuff happens and you're depending on stuff 'not' happening.  So in my experience, it's best if you don't rely on Faker to do this.  

That being said, i don't own it, i'm just speaking from my experience.  I wouldn't rely upon the faker library to do this.

one of the actual maintainers may have a wildly different opinion than i do :)

**Comment by Abrasha** [comment]
@trevershick, thank you for response

well, you are right. We shouldn't rely on 3'd party dependencies. But sublist in Java is kind of tricky and dangerous thing.

**Comment by trevershick** [comment]
Sure. But for arguments sake an ImmutableList could be returned (from Guava).  This still may cause an issue for you even if it doesn't have the same subList issues correct?

**Comment by Abrasha** [comment]
@trevershick, well
Here is an example.
I would like to test RedisTemplate with a lot of data.

It uses jdk serialization by default. In this case to must wrap the fake string list into serializable collection.

Fakers are mostly used to insert some test data set and if couldn't be serialized by default it is quiet unexpected. But this is my opinion

**Comment by trevershick** [comment]
Sure, i think i understand. However, it sounds like you have a defect in your code anyhow.  If you 'set' a list into your java object, just setting it like this:

```
public void setNames(List values) {
  this.names = values;
}
```

is a bad practice anyhow.  You should not be storing the reference to the list.  I could do this:
```
MyObject o = new MyObject();
List<String> names = new ArrayList<String>();
o.setNames(names);
assertThat(o.getNames(), is(empty()));
names.add("me");
assertThat(o.getNames(), is(empty())); // fails.
```

The setter accepting the list of names should be copying them.

**Comment by Abrasha** [comment]
@trevershick thank you for suggestion.

But now I realized that it is currently done in higher version of faker.

now the method looks like the following:

    public List<String> words(int num) {
        List<String> returnList = new ArrayList<String>();
        for (int i = 0; i < num; i++) {
            returnList.add(word());
        }
        return returnList;
    }

I user version `0.2` and now I upgraded it to `0.11` and is it pretty improved.

So the issue could be closed.

**Comment by trevershick** [comment]
ok. well i'm glad that worked out for you :)

happy coding.

**Comment by Abrasha** [comment]
@trevershick you too :+1:

**Comment by Abrasha** [comment]
@trevershick you too :+1:

**Comment by PascalSchumacher** [comment]
@Abrasha the latest version `0.12` is even better than `0.11` :)

**Comment by Abrasha** [comment]
@PascalSchumacher, thanks, I will definitely try it!

**Comment by Abrasha** [comment]
@PascalSchumacher the `0.12` version has not been indexed by https://mvnrepository.com/artifact/com.github.javafaker/javafaker yet (
