### ISSUE TITLE
Credit card number generator

### ISSUE THREAD

**Issue by Abrasha** [DiUS/java-faker#181]
What do you think about generating random card number verified with [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm)?

**Comment by PascalSchumacher** [comment]
already there: `faker.finance().creditCard()`  :)

see https://github.com/DiUS/java-faker/blob/f574317642a820fc24eef51a1a1fbafa02db2043/src/test/java/com/github/javafaker/FinanceTest.java

**Comment by Abrasha** [comment]
@PascalSchumacher nice, thanks!
Issue could be closed.

**Comment by PascalSchumacher** [comment]
@Abrasha You should be able to close the issue yourself.

**Comment by Abrasha** [comment]
@PascalSchumacher, sorry. I searched 'Close issue' button in the wrong place.
