### ISSUE TITLE
java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.loadAs

### ISSUE THREAD

**Issue by nitinmukhija** [DiUS/java-faker#187]
Hi

I have cloned the repo and trying to use the same in my project by doing below changes in pom.xml (as per the version of the cloned code):-

> <dependency>
>     		<groupId>com.github.javafaker</groupId>
>     		<artifactId>javafaker</artifactId>
>     		<version>0.13-SNAPSHOT</version>
> </dependency>

**But, I am getting below error on doing:-**
`Faker faker = new Faker(new Locale("en-IND"));`

```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;
	at com.github.javafaker.service.FakeValuesService.fakerFromStream(FakeValuesService.java:99)
	at com.github.javafaker.service.FakeValuesService.<init>(FakeValuesService.java:67)
	at com.github.javafaker.Faker.<init>(Faker.java:71)
	at com.github.javafaker.Faker.<init>(Faker.java:62)
```

Please suggest.

**Comment by nitinmukhija** [comment]
It works fine if I change the version to 1.12:-

> <dependency>
>     		<groupId>com.github.javafaker</groupId>
>     		<artifactId>javafaker</artifactId>
>     		<version>0.12</version>
> </dependency>

Please let me know the changes which have happened between these versions. I want to send a pull request, to add support for custom resource files. eg. adding a new file like en-INDIA.yml with more formats.

**Comment by codingricky** [comment]
@nitinmukhija I can't seem to reproduce your error. Do you have a failing test case that you can provide? And do all the tests (unit and integration) run for you?

**Comment by PascalSchumacher** [comment]
I tried to reproduce, but this works for me on current master:

``` java
@Test
public void test() {
  Faker faker = new Faker(new Locale("en-IND"));
  System.out.println(faker.address().city());
}
```

**Comment by codingricky** [comment]
Can't reproduce.

**Comment by NBS-LLC** [comment]
I ran into the same error (stack trace) with version 0.14 just by instantiating the Faker class. No locale info.

I was able to fix it by moving the Faker maven dependency to the top of the dependency list.

**Comment by steveinatorx** [comment]
i will add my report even though this is a stale issue: i got the same error when importing com.github.faker.* to a jmeter groovy script in faker version 0.16. Downgrading to the faker version 0.12 jar resolves this issue for me.
