### ISSUE TITLE
Birthday generator

### ISSUE THREAD

**Issue by andreldm** [DiUS/java-faker#208]
Please add a birthday generator to date() like this one:
https://github.com/blocoio/faker/blob/50e38e96b87aa12f0509658b931ac6d3455ec386/src/main/java/io/bloco/faker/components/Date.java#L59

This avoids the mess of passing Dates (seriously?LocalDate is much more sexier) values to faker.date().between();

**Comment by codingricky** [comment]
Any chance you would like to put in a PR?

**Comment by andreldm** [comment]
Absolutely. During the weekend I'll craft the code =)
