### ISSUE TITLE
how to select item of array/list/collection ?

### ISSUE THREAD

**Issue by RicoSchueppel** [DiUS/java-faker#211]
plz help .. where do i find doc ? 

i just want to randomly select  an item of an array

in faker.js (https://github.com/marak/Faker.js/) you can do this by 

Faker.random.arrayElement<string>(Makes); 
where Makes is an arbitrary array of something (objects), i.e. a List\<T\>

how to do this in java-faker ? 

----

you might have a workaround with something like:

List<User> ul = users.findAll();
z.setUser(ul.get(faker.random().nextInt(ul.size())));

but thats pretty ugly, isn't it ?

**Comment by codingricky** [comment]
@RicoSchueppel there isn't a feature to do that yet and yes what you have is probably one way to do that.

**Comment by denniss17** [comment]
Interesting, we have added this feature manually. Even added a method to select a random enum value. We added this (to the parent faker, javadoc omited for now)

```
	public <E> E randomElement(E[] array)
	{
		return array[this.number().numberBetween(0, array.length)];
	}

	public <E extends Enum<E>> E randomEnumValue(Class<E> enumeration)
	{
		return randomElement(enumeration.getEnumConstants());
	}

	public <E> E randomElement(List<E> list)
	{
		return list.get(this.number().numberBetween(0, list.size()));
	}
```

Let me see if I can quickly create a PR to add this to faker.random()
