### ISSUE TITLE
Import latest yaml file from stympy/faker

### ISSUE THREAD

**Issue by robosoul** [DiUS/java-faker#235]
With all of the current classes supported, we could import latest file from stympy/faker and support new classes like: DragonBall, Hobbit, HitchhikersGuideToTheGalaxy, etc...

@codingricky - Any thoughts ? What about new releases ?

-Luka

**Comment by codingricky** [comment]
@robosoul Yep do you want to pull over the latest file and start working on those classes?

**Comment by robosoul** [comment]
@codingricky - sure, I'll do it. Will open PR just for the file import and latter for each of the classes I implement.
