### ISSUE TITLE
Static `Faker` instance reference

### ISSUE THREAD

**Issue by mdomasevicius** [DiUS/java-faker#236]
It would be nice to have option for something like this: `Faker.default().internet().password()` out of the box.
I do understand that this could be achieved with a wrapper but *the best code to maintain is no code at all*.

I could contribute a pull request.
WDYT?

**Comment by GMadorell** [comment]
I was just thinking about the same thing!

**Comment by robosoul** [comment]
I think simply `Faker.instance()` would be enough since you can't have custom version(s) only the default one.
