### ISSUE TITLE
Generate random address within specified city

### ISSUE THREAD

**Issue by arthurdeschamps** [DiUS/java-faker#241]
Hi everyone,

First off thanks for this project, it's really useful and very efficient. Nice work !

I wanted to know if it was possible to generate an address within a specific city ?
I know we can use a Local object at Faker instantiation, but this seems to work only with countries. I'm building a simulation and need to be able to generate local, national and international addresses.

Thanks

**Comment by PascalSchumacher** [comment]
Sorry to say, but at the moment there is no way to do this.

**Comment by arthurdeschamps** [comment]
Ok, thanks for the reply. I'll try to take a look on my part when I'll have time.
