### ISSUE TITLE
Null/Empty values

### ISSUE THREAD

**Issue by idc101** [DiUS/java-faker#242]
Hi,

Is it possible to generate null/empty values for a certain percentage of output?

For example when generating company names, I'd like ~10% of them to be empty strings?

Thanks

**Comment by PascalSchumacher** [comment]
Sorry to say, but at the moment there is no way to do this.

**Comment by idc101** [comment]
How about something like this:
https://github.com/idc101/java-faker/tree/support-for-optional-values

API would look like:
```
    @Test
    public void testStreetAddressOptional() {
        final String streetAddressNumber = faker.optional(0.5).address().streetAddress();
        assertThat(streetAddressNumber, equalTo(""));

        final String streetAddressNumberOverrideDefault = faker.optional(0.25, "N/A").address().streetAddress();
        assertThat(streetAddressNumberOverrideDefault, equalTo("N/A"));
    }

    @Test
    public void testLatitudeOptional() {
        final String latitude = faker.optional(0.5, "Missing").address().latitude();
        assertThat(latitude, equalTo("N/A"));
    }
```

(These tests will fail randomly with those percentages!)

If you're happy with that as an API, happy to submit a PR for it.

**Comment by dewos** [comment]
@PascalSchumacher this would be really useful, it's a common pattner
