### ISSUE TITLE
Localization not correctly spreaded

### ISSUE THREAD

**Issue by Kaijiro** [DiUS/java-faker#246]
Hey,

I was playing around with your Java implementation of Faker (and using it in French) and I saw that not every feature has been localized (e.g. Chuck Norris facts).

I was wondering if it was worth to eventually submit a PR for I18N missing features or maybe you don't think it is a priority

**Comment by codingricky** [comment]
I would submit the PR to https://github.com/stympy/faker cause we sync it up from there from time to time.
