### ISSUE TITLE
Update maven tag to newest changes

### ISSUE THREAD

**Issue by Naimadnap** [DiUS/java-faker#249]
Last tag was updated more than 5 months ago

**Comment by PascalSchumacher** [comment]
Javafaker 0.14 was just released (see: https://search.maven.org/#artifactdetails%7Ccom.github.javafaker%7Cjavafaker%7C0.14%7Cjar) so this can be closed.

**Comment by Naimadnap** [comment]
@PascalSchumacher please update Readme.md :)

**Comment by PascalSchumacher** [comment]
Here you are https://github.com/DiUS/java-faker/pull/265 :)

**Comment by Naimadnap** [comment]
Great!
