### ISSUE TITLE
First names are in english when initiating faker with local "ru"

### ISSUE THREAD

**Issue by baubakg** [DiUS/java-faker#250]
Hello,

This is a great project:

Tested this with the russian locale:

`@Test
    public void testFaker() {
        Faker faker = new Faker(new Locale("ru"));

        String name = faker.name().fullName(); 

        System.out.println("fullname : "+name);

        String firstName = faker.name().firstName();

        System.out.println("firstname : "+firstName);

        String lastName = faker.name().lastName(); 

        System.out.println("last name : "+lastName);

        String streetAddress = faker.address().streetAddress(); 

        System.out.println("street address : "+streetAddress);

        System.out.println(faker.number().randomNumber());
    }`

The output is:

> fullname : Герман Белозеров
firstname : Katheryn
last name : Tremblay
street address : Свердлова ул., 216
21631654

As you can see although the fullname is in russian, the first and last name remain in english.

**Comment by PascalSchumacher** [comment]
Should be solved once https://github.com/DiUS/java-faker/pull/262 is merged.
