### ISSUE TITLE
I would like to pass a yaml file of my own making I.e Faker(File)

### ISSUE THREAD

**Issue by baubakg** [DiUS/java-faker#255]
Hi,

It would be nice to be able to pass a yaml file of my own making when initializing Faler.

`Faker faker = new Faker(new File("file path"))`

This will allow me to add / test customized yaml files, and be independant of the sentralized faker repository.

**Comment by baubakg** [comment]
Hi I managed to solve this without code change:

Two things needed to be done for a custom YAML file:

1. Create a unique file name. Let's say "zz.yml"
2. Put it under src/java/resources
3. Change the YAML file make the top node have the same name as your file name (In this example "zz")

If you decide to put it in a lower directory, you will need to include this information in the YML file.

example if your file is under : `src/main/resources/languages`, your yaml file should start with the node:
```
languages/zz:
    faker:
```

**Comment by PramodKumarYadav** [comment]
@baubakg : Thank you for the detailed solution. This is exactly what I was looking for!
