### ISSUE TITLE
Support generating card numbers

### ISSUE THREAD

**Issue by Abrasha** [DiUS/java-faker#257]
As an example we can take: https://github.com/VRMink/credit-card-generator
But be aware that is has GNU GPL License

**Comment by Abrasha** [comment]
Also we can find example Java in this gist: https://github.com/grahamking/darkcoding-credit-card/blob/master/RandomCreditCardNumberGenerator.java

**Comment by PascalSchumacher** [comment]
Java faker supports generating credit card numbers:

`new Faker().finance().creditCard()`

**Comment by Abrasha** [comment]
Wow, have not seen this. Thank you!
