### ISSUE TITLE
Would be great to have a better Javadoc

### ISSUE THREAD

**Issue by juanmbellini** [DiUS/java-faker#259]
Javadocs does not have a very good description. Would be great to have description on methods in order to know what each one does at a glance

**Comment by kinow** [comment]
+1, though I suspect it would be better to either keep it open and slowly add more documentation, or open one ticket per module/category/etc.

I have a post-it back at work with a class I struggled a bit to understand how to use. The note says "Write Javadoc and send a pull request" :-)

**Comment by PascalSchumacher** [comment]
I think pull requests are welcome.
