### ISSUE TITLE
Umlauts in email addresses

### ISSUE THREAD

**Issue by makkes** [DiUS/java-faker#272]
We are using the Faker with a German locale like this:
```java
final Faker faker = new Faker(Locale.GERMANY);
final String email = faker.internet().emailAddress();
```
The email addresses that are then generated sometimes contain umlauts which is incompatible to most MTAs.

**Comment by dagnelies** [comment]
As far as I understand, according to:

https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

https://tools.ietf.org/html/rfc6531

UTF8 in addresses are allowed as of 2012 ...how the MTAs deal with it in practice is another matter. Actually, generating UTF8 email addresses is a nice feature for testing. If you don't want them, just pick another locale. My 2 cents.
