### ISSUE TITLE
about "Usage with Locales"

### ISSUE THREAD

**Issue by msmvc** [DiUS/java-faker#277]
说明页面里说的用法是
Faker faker = new Faker(new Locale("{YOUR_LOCALE}"));
按这个写法运行时报错;
正确写法应该是下面这样,没有大括号
Faker faker = new Faker(new Locale("YOUR_LOCALE"));

**Comment by codingricky** [comment]
Are you saying I should remove the curly braces from the documentation?

**Comment by msmvc** [comment]
是的我说的就是这个意思

**Comment by tappava** [comment]
是的我说的就是这个意思 = yes thats what I mean

greetings

**Comment by msmvc** [comment]
yes. i found that you had removed the domo source "Faker faker = new Faker(new Locale("YOUR_LOCALE"));"
