### ISSUE TITLE
Performance of ZipCode

### ISSUE THREAD

**Issue by npvincent** [DiUS/java-faker#278]
Hi,

It seems there's a bit of a performance bottleneck with generating zipcodes as a new Generex object is instantiated every time a zipcode is requested.  Here's a quick (Kotlin) test script I knocked up:

```kotlin
fun main(args: Array<String>) {
	val sf = Faker(Locale("en","GB"), Random(1L))

	1.until(10).forEach {
		val iterations = 5000
		val start = System.currentTimeMillis()
		1.until(iterations).forEach { sf.address().zipCode() }
		val end = System.currentTimeMillis()

		println( "Producting ${iterations} zipcodes took ${end-start}ms (${(end.toDouble()-start.toDouble())/iterations.toDouble()}ms per record)")
	}
}
```

Running that with the current head of master produces these results on my laptop (JDK9):

```
Producting 5000 zipcodes took 10250ms (2.05ms per record)
Producting 5000 zipcodes took 6583ms (1.3166ms per record)
Producting 5000 zipcodes took 6409ms (1.2818ms per record)
Producting 5000 zipcodes took 6641ms (1.3282ms per record)
Producting 5000 zipcodes took 6731ms (1.3462ms per record)
Producting 5000 zipcodes took 6627ms (1.3254ms per record)
Producting 5000 zipcodes took 6776ms (1.3552ms per record)
Producting 5000 zipcodes took 6705ms (1.341ms per record)
Producting 5000 zipcodes took 6752ms (1.3504ms per record)
```

Hacking up a new version of FakeValuesService that cached the Generex objects so they are only created once for each regex provided these results:

```
Producting 5000 zipcodes took 472ms (0.0944ms per record)
Producting 5000 zipcodes took 255ms (0.051ms per record)
Producting 5000 zipcodes took 215ms (0.043ms per record)
Producting 5000 zipcodes took 153ms (0.0306ms per record)
Producting 5000 zipcodes took 147ms (0.0294ms per record)
Producting 5000 zipcodes took 161ms (0.0322ms per record)
Producting 5000 zipcodes took 183ms (0.0366ms per record)
Producting 5000 zipcodes took 99ms (0.0198ms per record)
Producting 5000 zipcodes took 89ms (0.0178ms per record)
```

Would there be any appetite to including this as an enhancement?  If so I'd be happy to propose a patch, but as we're targeting java 1.6 would the preferred approach be manual locking of the cache or a dependency on Apache Commons Collections?  Also, is there any expectation of instances of Faker being thread safe, as from a brief glance the Generex objects look to be internally stateful  so caching them would need to be done carefully considering the possibility of multi-threaded access to a single Faker?

Cheers,

Nick

**Comment by codingricky** [comment]
I don't mind improving performance but I don't want it to be at the expense of thread safety (even though I'm not sure if the current implementation is 100% thread safe) and over complicating the implementation. So if you could tick both boxes, then I'd be happy to incorporate any changes into the codebase. I hope that's not too much to ask :)

**Comment by dioxic** [comment]
Following the code through, caching of Generex objects would be thread-safe. The `Generex.random()` method does not using any of the internal state apart from the `automaton` object to get the initial state (which itself won't change).
