### ISSUE TITLE
Is there an option for "plugins"?

### ISSUE THREAD

**Issue by josejuanmontiel** [DiUS/java-faker#294]
The idea could be to "plug" some class to generate something very specific for my proyect... the name of my girlfriends...

name=faker.my.girlfriends

:)

**Comment by denniss17** [comment]
In our project we created an extension of the faker class in order to add our own faker methods. This is possible since https://github.com/DiUS/java-faker/pull/213

**Comment by josejuanmontiel** [comment]
Hi, I only starting dig in code.. i'm using it from beanmother proyect... i'll review more carefully what you said.

But originally i was thinking something more near to get inside this constructor

https://github.com/DiUS/java-faker/blob/master/src/main/java/com/github/javafaker/Faker.java

to use some "very specific feature" coded in my jar "along with the other great that was implemented before in faker library.

Thanks  for reply ;)
