### ISSUE TITLE
Invalid usernames and email addresses with some locales

### ISSUE THREAD

**Issue by jrodalo** [DiUS/java-faker#296]
Hi!

there is a problem with _usernames_ and _emails_ generation using the Spanish locale (the same may happen with other languages). Some names includes whitespaces so, in these cases, when generating the username we get something like `"josé luis.alonso"`. The method that generates emails is also based on the username, so in these cases we get invalid emails like `"josé luis.alonso@example.com"`.

Spanish names: https://github.com/DiUS/java-faker/blob/master/src/main/resources/es.yml#L56

### Example:

```java
Faker faker = new Faker(new Locale("es"));

String username = faker.name().username(); // "josé luis.alonso"
String email = faker.internet().safeEmailAddress(); // "josé luis.alonso@example.com"
```

### Java-Faker code:

```java
public String username() {
    return StringUtils.join(new String[]{
        firstName().replaceAll("'", "").toLowerCase(),
        ".",
        lastName().replaceAll("'", "").toLowerCase()}
    );
}

// ...

public String emailAddress() {
    return emailAddress(faker.name().username());
}
```

Maybe add another `replaceAll` to clean spaces or use `StringUtils.deleteWhitespace` on username method?

**Comment by jrodalo** [comment]
I've made a pull request (#297) that fixes this issue. Please, feel free to suggest any changes :)

**Comment by gregod** [comment]
Hi,
this is a follow up to this issue concerning mail servers not implementing the current RFC 6532 for international chars in email addresses (for example the mock smtp server [mailcatcher](https://mailcatcher.me/))

According to the older [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.2.3) the é in josé is not valid in the local part.

This is somewhat of an edge case but i think not much would be lost by following the older spec and doing a more aggressive character replacement on the local part.

**Comment by jrodalo** [comment]
Hi!

I've made another PR to remove accents in the local part. (#324)

Better late than never ;)
