### ISSUE TITLE
Random Alphanumeric values 

### ISSUE THREAD

**Issue by Varun-NS** [DiUS/java-faker#299]
How to generate an alphanumerical string of a specified length ?

**Comment by azakordonets** [comment]
Multiple options : 
1. faker.lorem().fixedString()
2. faker.letterify("????aaaa") -> will replace ? with random letter
3. faker.botify("????####aaaa") -> will replace ? with random letter and # with random number.

**Comment by baubakg** [comment]
Hi,

But these seem to be in latin despite instantiating faker with Japanese for example.

Example:

```
@Test
    public void testFakerRandomAlphaNumeric() {
        Faker faker = new Faker(new Locale("languages/jp"));
        System.out.println(faker.name().fullName());
        System.out.println(faker.lorem().fixedString(5));
        System.out.println(faker.letterify("????"));
    }
```

Only the first line spits out japanese text, but not the two last ones

**Comment by azakordonets** [comment]
Probably that's because there's no Japanese translation available? https://github.com/DiUS/java-faker/tree/master/src/main/resources - I don't see here Japanese resource file.

**Comment by baubakg** [comment]
Its there:
https://github.com/DiUS/java-faker/blob/master/src/main/resources/ja.yml

Sorry, I see that I copu pasted my local implementation a bit too much. Will adapt it accordingly.

**Comment by Jeff-Walker** [comment]
I'd still like a quick way to mix it up without a predefined pattern.
