### ISSUE TITLE
feature request : generate random chinese name?

### ISSUE THREAD

**Issue by qiangbro** [DiUS/java-faker#301]
feature request : generate random chinese name?

**Comment by JakimLi** [comment]
I guess this already implemented:

https://github.com/DiUS/java-faker/blob/master/src/main/resources/zh-CN.yml

Shouldn't `new Faker(forLanguageTag("zh-CN")).name().name()` work?

**Comment by qiangbro** [comment]
works.

    new Faker(Locale.SIMPLIFIED_CHINESE).name().name()
