### ISSUE TITLE
How to generate related faked data?

### ISSUE THREAD

**Issue by acnacion87** [DiUS/java-faker#309]
I would like to know if there is a way I can generate fake data (e.g Company and User info) with the details generated relates with each other?

For example if I generated a company name:
```
faker.company().name();
```
And the name generated is **Anderson Anderson**, i would want to generate emails like these examples:

- john.doe@anderson-anderson.com
- phil.hawk@aanderson.com
- tom.schwartz@aa.com

**Comment by codingricky** [comment]
Sorry this feature doesn't exist.
