### ISSUE TITLE
Choose Gender

### ISSUE THREAD

**Issue by ErikPartridge** [DiUS/java-faker#31]
It would be nice to be able to choose the gender of a name, is that at all possible?

**Comment by TheDerek** [comment]
Yeah I would like to know this as well. Also sorry for the bump.

**Comment by codingricky** [comment]
The difficulty is in sorting out the existing names and classifying them according to gender. I don't think programatically it would be difficult. It's just the manual task of going through all the names and saying whether they are male, female or both.

**Comment by harezmi1907** [comment]
I assume this is not resolved, right? That'd be great to have it.

**Comment by manueljordan** [comment]
Some addition or improvement for the next release? it is very valuable to generate the most real data

**Comment by berkarcan** [comment]
> The difficulty is in sorting out the existing names and classifying them according to gender. I don't think programatically it would be difficult. It's just the manual task of going through all the names and saying whether they are male, female or both.

But it would be useful to have them as other options, like female_name, male_name. These may not be the same with the fake names. There are already some lists of males and females  in the web like: https://gist.github.com/BenjaminAdams/4f6175e7ede6af50e9ee

**Comment by bodiam** [comment]
@berkarcan  shouldn't be too hard to do, most language files already have a split between male and female names. However, this library is no longer maintained, and I'm maintaining an active fork here (https://github.com/datafaker-net/datafaker). If you  would  like to contribute such a feature, that would be most welcome.
