### ISSUE TITLE
Support for E.164 Phone Numbers

### ISSUE THREAD

**Issue by patrickbray** [DiUS/java-faker#312]
Hi 

Thanks for porting this library across to the JVM it makes our test data generation a lot more enjoyable.   

Just wondering if it would make sense to add a function to get a valid [E.164](https://en.wikipedia.org/wiki/E.164) formatted phone number? 

If so I could look at submitting a PR for this? 

Thanks

**Comment by codingricky** [comment]
@patrickbray sorry for the delay, yes you can submit a PR if you want for this feature.
