### ISSUE TITLE
Please add browser user-agent Faker

### ISSUE THREAD

**Issue by bkalbfus** [DiUS/java-faker#336]
Either use real-world data like https://pypi.org/project/fake-useragent/
or use snapshot cache like https://github.com/mkstayalive/random-user-agent-java

**Comment by codingricky** [comment]
would you like to submit a PR?

**Comment by haruntuncay** [comment]
Hey @bkalbfus, if you don't have the time or interest to submit a PR, please let me know.
@codingricky, I would be happy to submit it.

**Comment by bkalbfus** [comment]
Thanks for asking.  Please submit with whatever method you prefer.  I saw
some browser-agent entries in the yml files, but I had to choose just one
browser type (I used the code:  faker.resolve("internet.user_agent.chrome")
).  It'd be useful to simply get a random agent string and maybe have it
weighted according to popularity.

Thanks again!  Faker has been very easy to use!

-Brian

**Comment by codingricky** [comment]
I wouldn’t worry about weighting by popularity... no other method does that and the point is just to get random data quickly. Thanks!

**Comment by haruntuncay** [comment]
Hey @bkalbfus, so what you want implemented is just a way to get a browser agent without choosing one beforehand, right ? So, do you think something like the below would be okay?

`faker.resolve("internet.user_agent")` or `faker.resolve("internet.user_agent.rand")`

Also, do you think there should be more values per each browser vendor ?

**Comment by bkalbfus** [comment]
I tried `faker.resolve("internet.user_agent")` first in hopes that it would randomize all sub-lists, but that didn't work.   I guess that would be a good place to put all values.  It would be good to have it called fluently like other fakers:   `faker.internet.userAgent()`
If we want to keep the choice of which browser easy, then we can have:
`faker.internet.userAgent().any()` 
`faker.internet.userAgent().chrome()`
`faker.internet.userAgent().internetExplorer()`
`faker.internet.userAgent().firefox()`
`faker.internet.userAgent().opera()`

I recommend taking a healthy sampling from real-world agent strings like in one of the examples I cited, especially the longest and shortest.

**Comment by codingricky** [comment]
maybe you can do something like https://github.com/stympy/faker/blob/master/lib/faker/default/internet.rb and take in an enum being the vendor (browser)

**Comment by haruntuncay** [comment]
Thank you both for the suggestions. I am free for the 2 following days, starting to work on it right now. 😄

**Comment by codingricky** [comment]
No rush, thanks

**Comment by haruntuncay** [comment]
Hi @bkalbfus, I was able to add the feature you requested today. 
Could you please check it out and provide a feedback on whether it will do your job or not ?
Thank you.

**Comment by bkalbfus** [comment]
I checked it out, built it, and referenced the snapshot in my code with the function you added.  It works perfectly and the use is obvious!

A side note - the first build resulted in a test failure of the type that faker is meant to expose.  See attached test results.  Apparently there is a currency called "Pa`anga" that doesn't fit the regular expression being tested for.

[com.github.javafaker.CountryTest.txt](https://github.com/DiUS/java-faker/files/2861684/com.github.javafaker.CountryTest.txt)


Thanks a lot!  I will look for the next release.

**Comment by haruntuncay** [comment]
> 
> 
> I checked it out, built it, and referenced the snapshot in my code with the function you added. It works perfectly and the use is obvious!
> 
> A side note - the first build resulted in a test failure of the type that faker is meant to expose. See attached test results. Apparently there is a currency called "Pa`anga" that doesn't fit the regular expression being tested for.
> 
> [com.github.javafaker.CountryTest.txt](https://github.com/DiUS/java-faker/files/2861684/com.github.javafaker.CountryTest.txt)
> 
> Thanks a lot! I will look for the next release.

I am glad it worked out well. Also, thank you for pointing out the test case issue.
