### ISSUE TITLE
Add locale for Argentina (es-AR) 

### ISSUE THREAD

**Issue by gmarti28** [DiUS/java-faker#337]
There is no locale available for Argentina  

I'd like to add myself a new locale for supporting valid addresses and other fakes in Argentina

It would be nice if I got permission to branch, add the new locale and create the needed PR

**Comment by codingricky** [comment]
Feel free to create the PR and submit when ready.

**Comment by gmarti28** [comment]
Rick, I don't have permissions to commit yet.

**Comment by codingricky** [comment]
Anyone can submit a PR
