### ISSUE TITLE
Fake values assigned through Faker annotations

### ISSUE THREAD

**Issue by thiagolocatelli** [DiUS/java-faker#342]
I was thinking about writing a PR to include the following requirement.

A java class could have it's attributes annotated with annotations from faker and two methods would be created. One receiving an existing instance of the class and one receiving a class type T. The first method would inject the fake values in the attributes annotated and the second method would create an instance of type T, include fake values and return the bean.

```java
public class Person {

    @FirstName
    private String name;

    @LastName
    private String lastName;

    @DateOfBirth
    private Date dateOfBirth;

    @Email
    private String email;

    @Job
    private String job

    @Address        
    private Address homeAddress;
    
}
```

and then we would do

```java
Faker faker = new Faker();
Person personOne = new Person();
faker.fakeBean(p);
Person personTwo = faker.fakeType(Person.class)
```

Would something like that be welcomed? I find myself calling 'faker.name().fullName()' multiple times when I wish I could just pass my object and have Faker do the work.

**Comment by codingricky** [comment]
I think this would be big enough to warrant its own project independent of java-faker.
