### ISSUE TITLE
No .address().city()

### ISSUE THREAD

**Issue by ygnessin** [DiUS/java-faker#35]
I see the methods `.cityPrefix()` and `.citySuffix()` but there doesn't seem to be a simple `.city()` method, which stympy/faker does have: https://github.com/stympy/faker#fakeraddress

**Comment by PascalSchumacher** [comment]
Hi everybody,

this issue can be closed. `address().city()` was added with dbd8b634351136166e3c43888ca4861f3b8fa7b7 and released with version 0.7.

**Comment by ygnessin** [comment]
Thank you!
