### ISSUE TITLE
Country Names,Flags & Codes

### ISSUE THREAD

**Issue by ckurtm** [DiUS/java-faker#351]
is it possible to add a country property where u can get country name, city, code,flag and all?

**Comment by aminsoheyli** [comment]
Yeah✔, it's possible.
If you can, please do it, and then make a pull request.

**Comment by ckurtm** [comment]
done :) https://github.com/DiUS/java-faker/pull/353

**Comment by aminsoheyli** [comment]
Thanks🌹❤
