### ISSUE TITLE
Foreign Addresses?

### ISSUE THREAD

**Issue by sachsgit** [DiUS/java-faker#359]
Hi,

Tried:
```
        Locale loc = new Locale(locale);
        String address = new Faker(loc).address().fullAddress();
        System.out.println("Address from " + loc + ": \"" + address + "\".");
        
        Faker frenchFaker = new Faker(Locale.FRANCE, new Random());
        System.out.println("Address in France: \"" + frenchFaker.address().fullAddress() + "\".");
```
and I got:
```
Address from en-sg: "Apt. 601 61 Woodlands St 2, Footon, MI 093103".
Address in France: "1 étage 0 Allée, Voie Monsieur-le-Prince, Pessac, NM 34419".
```
Are these valid? I ask because what little research into international mailing address I did, I found:
* Use all capital letters.
* Type or legibly write the address in English.
* Use no more than 5 lines, including:
 1. Addressee's name
 2. Street address or P.O. box number
 3. City or town, principal subdivision such as province, state, or county, and postal code. In some countries, the postal code may precede the city or town.
 4. Country name

Does seems to be US-Mail to Foreign, but, thoughts?

**Comment by codingricky** [comment]
I don't think they adhere to any rules around international mailing addresses
