### ISSUE TITLE
Flanky tests MedicalTest#testMedicineName

### ISSUE THREAD

**Issue by iaguera** [DiUS/java-faker#371]
Regular expression does not fit in values like:
- HYDROXYETHYL STARCH 130/0.4
- GUANGXI YULIN PHARMACEUTICAL GROUP CO LTD
- COMOCLADIA DENTATA BARK/LEAF

in MedicalTest#testMedicineName.

**Comment by codingricky** [comment]
Fixed with https://github.com/DiUS/java-faker/pull/404
