### ISSUE TITLE
Random generation for java.time.LocalDate

### ISSUE THREAD

**Issue by Ryuuji159** [DiUS/java-faker#372]
Apparently there isn't any for this, just regular date but that class has his own problems and I try to avoid it when I can.

**Comment by josepj** [comment]
Meanwhile, you can convert the java.util.Date object to a java.time.LocalDate object.
```java
Date date = new Date();
LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
```
Reference: https://stackoverflow.com/a/21242111/7061377

**Comment by Ryuuji159** [comment]
I know I can do it that way but that transformation a litte ugly to my taste, so if it where natively in the library, at the moment i have a wraper for that part

**Comment by codingricky** [comment]
I'm trying to keep compatibility with 1.6 for as long as I can and since `LocalDate` was introduced in 1.8 it would break that.

**Comment by bodiam** [comment]
@codingricky Is there any reason at this moment to keep 1.6 compatibility? Even Android is on 1.8 now. It would be nice to be able to use the Java 8 time api.
