### ISSUE TITLE
Method faker.number().digits(7)) return less than the number of characters passed in the parameter

### ISSUE THREAD

**Issue by DenisKozachok** [DiUS/java-faker#381]
**Steps reproduce:**
1) Call method  testNumberDigitMethod();

**Expected result:**
All values are equal to the number of characters passed in the parameter

**Actual result:**
Return less than the number of characters passed in the parameter

**Test method:**
```
public int testNumberDigitMethod(){
int minVal = 999999999;
        int lenthDigit = 7;
        for (int i = 0; i < 10000; i++) {
            int val = Integer.parseInt(new Faker().number().digits(lenthDigit));
            System.out.println(val);
            if(minVal > val){
                minVal = val;
            }
        }
       System.out.println("minVal = " + minVal);
 return minVal;
}
```

**Return value:**
```
7048853
9756633
4545
5330498
3024871
138146
5723367
524530
6353369
5013284
15651
214186
4240892
.....
```

**Comment by codingricky** [comment]
It returns a string... the string should be the length of the digit passed in.. I think as you're converting the value to an Integer anything that has a leading zero will be lost so it'll appear shorter in length.. @DenisKozachok does that make sense?
