### ISSUE TITLE
RunTimeException: {} results in null expression

### ISSUE THREAD

**Issue by sachsgit** [DiUS/java-faker#394]
I tried to compile my own jar file and when I try to use it, I get:

> Exception in thread "main" java.lang.RuntimeException: name.first_name resulted in null expression
>	at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:331)
>	at com.github.javafaker.Name.firstName(Name.java:66)
>	at javaFaker.FakerLoop.main(FakerLoop.java:10)

my code is
```
public class FakerLoop {
    private static final Faker faker = new Faker();
    
    public static void main(String[] args) {
    	for (int i = 0; i < 10; i++) {
    	    String firstName = faker.name().firstName();
    		System.out.println("First Name[" + i + "]: \"" + firstName + "\" [" + firstName.length() + "]");
    	}   	
    }  
}
```
I am using
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<jardesc>
    <jar path="java-faker/bin/javaFaker_0.18.1.jar"/>
    <options buildIfNeeded="true" compress="true" descriptionLocation="/java-faker/META-INF/javaFaker.jardesc" exportErrors="false" exportWarnings="false" includeDirectoryEntries="false" overwrite="false" saveDescription="true" storeRefactorings="false" useSourceFolders="false"/>
    <storedRefactorings deprecationInfo="true" structuralOnly="false"/>
    <selectedProjects/>
    <manifest generateManifest="false" manifestLocation="/java-faker/META-INF/MANIFEST.MF" manifestVersion="1.0" reuseManifest="false" saveManifest="false" usesManifest="true">
        <sealing sealJar="false">
            <packagesToSeal/>
            <packagesToUnSeal/>
        </sealing>
    </manifest>
    <selectedElements exportClassFiles="false" exportJavaFiles="true" exportOutputFolder="true">
        <javaElement handleIdentifier="=java-faker/src\/main\/resources"/>
        <javaElement handleIdentifier="=java-faker/src\/main\/java"/>
    </selectedElements>
</jardesc>
```

I have debugged the code and the "fault" seems to be with:
```FakerValuesServices.java:211    currentValue = ((FakeValuesInterface) currentValue).get(currentPath);```

where `currentPath` is `name` and should allow the name.yml to be accessed.
Instead, it returns `null`

Can anyone tell me what I am doing wrong?

**Comment by codingricky** [comment]
which version are you using? you seem to have 0.18.1

**Comment by sachsgit** [comment]
I forked the project, pulled the latest code base, added some personal additional code.
I ran all the JUnit tests, which all passed.
I created a jar file using the above jardesc file, and tried to use it in another project area.
That is where the error come from. It works within the project, but not as a jar file.

**Comment by codingricky** [comment]
Sorry I'm not sure I can help you in this case, I'm not sure what you've changed.
