### ISSUE TITLE
Consider giving up on snake yaml dependency

### ISSUE THREAD

**Issue by alexcom** [DiUS/java-faker#395]
Greetings

Recently I  had some dependency issues related to snake yaml and was surprised that such small library uses this unnecessary dependency just for reading resource files. IMHO there's no reason to bring yaml parser transitively into another people's projects. I suggest you to eventually modify java-faker's code to discard this dependency. There's a number of options to chose from. You can convert yaml files to pure java files either manually or automatically during build process. You can use one of the file formats with parsers  included in JDK. Etc.

What do you think?

**Comment by codingricky** [comment]
I take your point but I feel having it in yaml keeps things simple especially when you can use yaml files from the original ruby faker library.
