### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [DiUS/java-faker#399]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/javafaker/Crypto.java: Line number => 35: API name => MessageDigest:<BR> File name => src/main/java/com/github/javafaker/Crypto.java: Line number => 32: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by codingricky** [comment]
This is only used for generating fake data so it doesn't matter if we're using an outdated algorithm.
