### ISSUE TITLE
version 0.6 not (yet?) in maven central?

### ISSUE THREAD

**Issue by PascalSchumacher** [DiUS/java-faker#46]
Maven can not download version 0.6 and http://search.maven.org tells me the latest version is 0.5.

Thanks for providing java-faker. :)

**Comment by jitpack-io** [comment]
Hi all
If you want to quickly get the latest release from GitHub, you can use:
https://jitpack.io/#DiUS/java-faker/javafaker-0.6

**Comment by codingricky** [comment]
Try again @PascalSchumacher

**Comment by PascalSchumacher** [comment]
Works now. Thanks!
