### ISSUE TITLE
Regexify doesn't handle metacharacters inside of square brackets

### ISSUE THREAD

**Issue by mdentremont** [DiUS/java-faker#486]
The following:
![image](https://user-images.githubusercontent.com/1106324/77068431-5db77780-69c5-11ea-8ce9-6db12861d621.png)

Should behave the same (or at least similar - I omitted some characters) to:
![image](https://user-images.githubusercontent.com/1106324/77068394-4b3d3e00-69c5-11ea-8ff2-12a605cd8c68.png)

It appears to get confused by the metacharacters at the beginning, and then applies the repeat to the `]`

**Comment by nanfang-wuyu** [comment]
Our gruop have looked carefully at your issue and we're interested. We will try to solve this problem.

--SE_CHWJ

**Comment by VG-Huai** [comment]
Unfortunately, our team are unable to handle this problem. Java-faker uses another java library called 'Generex' to generate strings from regex. It seems that 'Generex' doesn't allow users to write `//w` or `//b` inside `[]`, the meaning of `[\\w\\d]{5}` is same as `\\w\\d]{5}`. You can see it in the image shown below.
![-20f869a040ddc662](https://user-images.githubusercontent.com/56375896/115960338-658c0880-a543-11eb-850d-2e98088c12b9.png)

**Comment by nanfang-wuyu** [comment]
Besides that described by VG-Huai, we also find if you want to generate the similar String to "faker.regexify("[a-zA-Z0-9]{5}")", you can change the regex from "faker.regexify("[\\w\\d]{5}");" to "faker.regexify("(\\w|\\d){5}")", which might give you expected result as the picture shown.
There would appear underlines for most cases, I guess that's what you meant "omitted some characters".

![issue_#486](https://user-images.githubusercontent.com/60834053/115960669-5c03a000-a545-11eb-933d-638305879317.png)
