### ISSUE TITLE
testHungarianZipCodeByState() sometimes failed.

### ISSUE THREAD

**Issue by irakatz** [DiUS/java-faker#497]
**Describe the bug**
"testHungarianZipCodeByState()" sometimes failed.
**To Reproduce**
If we increase testing times, this can be reproduced. For example

    @Test
    public void testHungarianZipCodeByState() {
        for(int i=0;i<10;i++){
            faker = new Faker(new Locale("hu"));
            assertThat(faker.address().zipCodeByState(faker.address().stateAbbr()), matchesRegularExpression("[0-9]{4}"));
        }
    }
**Expected behavior**
It should be passed.

**Versions:**
 - OS: Win10
 - JDK 1.8
 - Faker Version 1.0.2

**Comment by JinquanPeng** [comment]
I think the bug is caused by the function `Yaml.loadAs()`. It treats `NO` as `false`.  So the program cannot find the key `NO`.
