### ISSUE TITLE
Should create random boolean value.

### ISSUE THREAD

**Issue by douglaslee1990** [DiUS/java-faker#51]

**Comment by codingricky** [comment]
Why wouldn't you use the nextBoolean from java.util.Random?

**Comment by douglaslee1990** [comment]
So, I can and that is what I do right now but since I am already implementing faker it would be nice if faker just had a method to do that for me instead of me having to either:
- write a really short method to do it
- write that code locally

Not a big deal either way, but I thought it would be nice to have it in there.

**Comment by codingricky** [comment]
I'm going to leave it out at the moment. I don't think there's a great deal of value in wrapping methods from java.util.Random in the Faker libraries.

**Comment by PascalSchumacher** [comment]
@douglaslee1990 Since version 0.9 java-faker supports generating booleans: https://github.com/DiUS/java-faker/commit/4cda6064e5f1acb952463302545667c9b0ffda51

Cheers,
Pascal
