### ISSUE TITLE
Firefox instances are not opening more than 5 inside container in docker.

### ISSUE THREAD

**Issue by LakshmiNagandla** [DiUS/java-faker#521]
**Describe the bug**
Firefox instances are not opening more than 5 instances inside container in docker

**To Reproduce**
To open firefox browser we have used below version of the code 

Docker command: 
--------------------------
docker run -d -p 5903:5900 --link selenium-hub:hub -v /dev/shm:/dev/shm -e NODE_MAX_INSTANCES=15 -e NODE_MAX_SESSION=15 selenium/node-firefox-debug:3.141.59-20200409

Desired Capabilities: 
-----------------------------
DesiredCapabilities capabilities = DesiredCapabilities.firefox(); capabilities.setCapability("unexpectedAlertBehaviour", "ignore"); //capabilities.setPlatform(Platform.fromString(os.toUpperCase())); capabilities.setCapability("maxDuration", 3600); driver = new RemoteWebDriver(hubURL, capabilities);

**Expected behavior**
Firefox browser instances are not opening beyond 6 instances inside the container. Do you have any solution for this

**Comment by schallerala** [comment]
How is this related to this project?
