### ISSUE TITLE
Maintaining compatibility with Java 1.6

### ISSUE THREAD

**Issue by schallerala** [DiUS/java-faker#558]
**Is your feature request related to a problem? Please describe.**
It is indirectly related to a problem. The _problem_ is for future contributions. It puts the community a strong limitation, as the Java community is mainly working with Java 8 and higher.

Also, a question to the _ruling_ contributors. Why put this JDK 6 limitation, when in the Travis CI, it isn’t running tests with this Java version?

**Describe the solution you'd like**
Let’s lift the limitation to JDK 8.

**Describe alternatives you've considered**
JDK 11?

**Additional context**
~~none~~

**Comment by codingricky** [comment]
It’s for Android compatibility.
