### ISSUE TITLE
Fix "en-ZA" ID number is invalid

### ISSUE THREAD

**Issue by Diboiza** [DiUS/java-faker#566]
**Describe the bug**
ID number for Locale "en-ZA"
produces id in format ###-##-####
instead of "en-ZA" formart: 
id_number:
      formats: ["##########08#"]

**To Reproduce**
new Faker(new Locale("en-ZA").idNumber().valid()
new Faker(new Locale("en", "ZA").idNumber().valid()

**Expected behavior**
ID number to be in formats: ["##########08#"]
E.g 8904115234088

**Versions:**
 - OS: Winsods
 - JDK 1.8
 - Faker Version 1.0.2

**Additional context**

**Comment by 2235161562** [comment]
Hello, I have fixed this problem in PR#619
The issue of ID number for Locale "en-ZA" can be close.

Past result of ID number for Locale "en-ZA" is:  ###-##-####
Now, it is:  YYMMDDSSSSCAZ
[YYMMDD is birthday, SSSS is serial number and 0000-4999 is female, C is 0 or 1, A is 8, Z is check number of Luhn algorithm]

Versions:
- OS: Winsods
- JDK 1.8
- Faker Version 1.0.2

**Comment by Diboiza** [comment]
Thank you so much
