### ISSUE TITLE
Problem with date().past()

### ISSUE THREAD

**Issue by muhvit** [DiUS/java-faker#64]
public Date past(int atMost, TimeUnit unit) {
        Date now = new Date();
        Date aBitEarlierThanNow = new Date(now.getTime() - 1000);
        return future(atMost, unit, aBitEarlierThanNow);
    }

Shouldn't this be calling past() rather than future()? Worked around this by calling the 3 parameter form.

**Comment by codingricky** [comment]
Fixed as part of d98849eb738809269cb1164ddfdc69069c8e0743
