### ISSUE TITLE
Need email , how can i get fake email?

### ISSUE THREAD

**Issue by immujahidkhan** [DiUS/java-faker#657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by immujahidkhan** [comment]
found

**Comment by guissalustiano** [comment]
For future note: `faker.internet().emailAddress()`

**Comment by bodiam** [comment]
@guissalustiano See https://github.com/datafaker-net/datafaker for an improved version of this library.
