### ISSUE TITLE
Faker Error: java.lang.NoClassDefFoundError: java/sql/Date

### ISSUE THREAD

**Issue by echavez-eb** [DiUS/java-faker#706]
**Describe the bug**
Getting the following exception error when using **faker** to get a _fake anything_, as _expected_...

`Error: java.lang.NoClassDefFoundError: java/sql/Date`

**To Reproduce**
As simple as...
```
import com.github.javafaker.Faker;
import java.sql.Date; //This is not needed by MY class, but based on the exception, faker is asking for it.
public class FakerFails {
    public void fakerFails(){
        try{
            Faker faker = new Faker();
            String streetName = faker.address().streetName();
            if (!streetName.isEmpty()){
                System.out.println(streetName);
            }
        }catch(Throwable e){
            System.out.println("Error: "+e);
        }
    }
}
```

**Expected behavior**
Let me think... a street name, printed on the console?

**Versions:**
 - Faker Version 1.0.2
 - OS: Windows 10
 - JDK 17
```
$ java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Additional context**
(Hope this is enough to use "faker")

- System Information:
- Runtime version: 11.0.13+7-b1751.25 amd64
- Windows 10 10.0
- GC: G1 Young Generation, G1 Old Generation
- Memory: 2040M
- Cores: 12
- Processor	Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
- Installed RAM	16.0 GB
- System type	64-bit operating system, x64-based processor
- Edition	Windows 10 Home
- Version	21H2
- Installed on	‎4/‎28/‎2021
- OS build	19044.1526
- Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by bodiam** [comment]
Hi @echavez-eb , Javafaker is no longer maintained, please have a look at www.datafaker.net, which is a modern port of Javafaker, and which is tested on Java 8, 11 and 17 (and the  above code of course works with Datafaker)

**Comment by ThreeHmeng** [comment]
Hello @echavez-eb, our group are interested in this issue, and we will try to fix it.
---- SE_SUSTech, group: Lanrand

**Comment by echavez-eb** [comment]
> Hi @echavez-eb , Javafaker is no longer maintained, please have a look at [www.datafaker.net](http://www.datafaker.net), which is a modern port of Javafaker, and which is tested on Java 8, 11 and 17 (and the above code of course works with Datafaker)

Really? So why are there pull requests completed from a month ago? Anyway, if the new faker works, fine for me. I'll check it out, thanks Bodiam.
