### ISSUE TITLE
Version of dk.brics.automaton (java-faker dependency) has a bug that breaks maven/gradle plugins, newer versions contain fix

### ISSUE THREAD

**Issue by StevenPG** [DiUS/java-faker#709]
**Describe the bug**
Usage of version 1.11-8 of dk.brics.automaton results in issues using certain gradle and maven plugins.

Reference: https://app.bountysource.com/issues/36726064-pom-missing-xml-declaration-legible-by-sbt-is-rejected-by-coursier
Reference: https://github.com/coursier/coursier/issues/316

**To Reproduce**
Create a project that uses any version of java-faker from 1.0.2 or earlier, us any plugin that attempts to read dependency information, such as cyclonedxBom

**Expected behavior**
Projects using java-faker are able to successfully execute a plugin that processes dependencies by reading dk.brics.automaton dependency's parent pom/pom.

**Versions:**
 - Any OS
 - Any JDK
 - Any JavaFaker version

**Additional context**

I think this is just a simple case of an issue being identified in a dependency version that's long since been updated.

As per a github issue, dk.brics.automaton found the error in 1.11-8 and fixed it in 1.12.x versions. The dependency was also renamed. We're unable to keep using java-faker until we can get this issue remediated, simply because we can't just update the dependency version and override the transitive dependency, because the GAVC changed.

Issue: https://github.com/cs-au-dk/dk.brics.automaton/issues/4 (June 22, 2017)

Currently in java-faker: 
// https://mvnrepository.com/artifact/dk.brics.automaton/automaton
implementation 'dk.brics.automaton:automaton:1.11-8'

Updated dependency
// https://mvnrepository.com/artifact/dk.brics/automaton
implementation 'dk.brics:automaton:1.12-4'

**Comment by bodiam** [comment]
@StevenPG this is not a dependency of javafaker, but of generex. How do you expect this dependency to be changed here?

**Comment by StevenPG** [comment]
> @StevenPG this is not a dependency of javafaker, but of generex. How do you expect this dependency to be changed here?

Looks like I was too hasty when I was looking through the dependency tree.

Guess it just won't be possible for any of those pom parsing plugins to be compatible with javafaker for the foreseeable future.

Cheers

**Comment by bodiam** [comment]
@StevenPG well, this library isn't really maintained anyway, that's why I created https://github.com/datafaker-net/datafaker, which is a fork of this library, but it's a bit tricky to fix, since generix is also no longer maintained, and it's tricky to find a decent Regex replacement library, none of them seem to be maintained.
