### ISSUE TITLE
address().city() throws exception female_first_name male_first_name

### ISSUE THREAD

**Issue by paulschwarz** [DiUS/java-faker#732]
**Describe the bug**

`Faker.instance().address().city()` sometimes:

- returns "Abernathyhaven"
- throws "Unable to resolve #{female_first_name} directive."
- throws "Unable to resolve #{male_first_name} directive."

**To Reproduce**

Spuriously observed when running the following multiple times until you hit the issue:

- `Faker.instance().address().city()`
- `Faker.instance().address().streetAddress()`

**Expected behavior**

Always return a city.

**Versions:**
 - OS: Windows 10
 - JDK: 11 Correto
 - Faker Version: 1.0.2

**Comment by paulschwarz** [comment]
Never mind. I had extended the `Name` class with my own `NameExtension` class.

When calling `Faker.instance().address().streetAddress()` it actually picks a "name" and then puts a street/road/whatever ending on it. As a hidden consequence, when I introduced my extension, it was no longer able to make a "name" when trying to make a "street address".

**Comment by bodiam** [comment]
Hi @paulschwarz , any reason in particular why you are using Javafaker instead of Datafaker (https://github.com/datafaker-net/datafaker/)?

Datafaker is a maintained fork, with the security issues of Javafaker fixed, more fakers, and it's 10 to 100 times faster in most cases.

**Comment by paulschwarz** [comment]
@bodiam thanks for letting me know about this. I'm trying it out now.

**Comment by bodiam** [comment]
@paulschwarz no worries, and good luck. Please let us know if you run into any issues. You shouldn't, but you never know :)
