### ISSUE TITLE
Add minecraft to the Faker

### ISSUE THREAD

**Issue by Gennario** [DiUS/java-faker#758]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, it's a huge problem!

**Describe the solution you'd like**
Please add a Minecraft faker.

**Describe alternatives you've considered**
It's as simple as adding Minecraft faker.

**Additional context**
There is no other context.

**Comment by bodiam** [comment]
We already have minecraft:

https://www.datafaker.net/documentation/providers/#number-of-providers-per-datafaker-version
