### ISSUE TITLE
The faker.date() method returns different dates when using seed

### ISSUE THREAD

**Issue by remMirakl** [DiUS/java-faker#769]
**Describe the bug**
When using a seed, the faker.date() method returns different dates. Indeed, the faker.date() seems to use the current date to generate a random date. So when the method is used another day, the result will be different. This behavior can break tests.

**To Reproduce**
You can easily reproduce this bug by using a seed and use the faker.date() in a simple test that checks the date returned by the method. 

**Expected behavior**
If you launch the test another day that the day you created it, the test will fail since the date returned will not be the same.

**Comment by bodiam** [comment]
This is a known issue, and is fixed in Datafaker

**Comment by remMirakl** [comment]
Thank you for your answer!
